repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
      args: ['--unsafe']
    - id: check-toml
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "google", ]
- repo: https://github.com/google/yapf
  rev: v0.32.0
  hooks:
    - id: yapf
      additional_dependencies: [toml]
      args: [--style, google]
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.8.2
  hooks:
    - id: commitizen
      stages:
        - commit-msg
- repo: https://github.com/sondrelg/pep585-upgrade
  rev: v1.0
  hooks:
    - id: upgrade-type-hints
      args: [--futures=true]
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.7
  hooks:
    - id: docformatter
      language: python
      additional_dependencies: [tomli]
      args: [--config, ./pyproject.toml]
